### PR TITLE
Ecdar-API Services and Message types (group 1 & 2)

### PR DESCRIPTION
**Pull request by sabotack**
Implemented two new services, their methods and their Message types.

- Added service `EcdarApi` with gRPC methods:
  - `GetProject(GetProjectRequest) returns (GetProjectResponse)`
  - `CreateProject(CreateProjectRequest) returns (CreateProjectResponse)`
  - `UpdateProject(UpdateProjectRequest) returns (google.protobuf.Empty)`
  - `DeleteProject(DeleteProjectRequest) returns (google.protobuf.Empty)`
  - `ListProjectsInfo(google.protobuf.Empty) returns (ListProjectsInfoResponse)`
  - `ListAccessInfo(ListAccessInfoRequest) returns (ListAccessInfoResponse)`
  - `CreateAccess(CreateAccessRequest) returns (google.protobuf.Empty)`
  - `UpdateAccess(UpdateAccessRequest) returns (google.protobuf.Empty)`
  - `DeleteAccess(DeleteAccessRequest) returns (google.protobuf.Empty)`
  - `UpdateUser(UpdateUserRequest) returns (google.protobuf.Empty)`
  - `DeleteUser(google.protobuf.Empty) returns (google.protobuf.Empty)`
  - `GetUsers(GetUsersRequest) returns (GetUsersResponse)`
  - `CreateQuery(CreateQueryRequest) returns (google.protobuf.Empty)`
  - `UpdateQuery(UpdateQueryRequest) returns (google.protobuf.Empty)`
  - `DeleteQuery(DeleteQueryRequest) returns (google.protobuf.Empty)`
  - `SendQuery(SendQueryRequest) returns (SendQueryResponse)`
  - `DeleteSession(google.protobuf.Empty) returns (google.protobuf.Empty)`

- Added service `EcdarApiAuth` with gRPC methods:
  - `GetAuthToken(GetAuthTokenRequest) returns (GetAuthTokenResponse)`
  - `CreateUser(CreateUserRequest) returns (google.protobuf.Empty)`
  - `Endpoints(google.protobuf.Empty) returns (EndpointsResponse)`

### CODE REVIEW

**Comment by atjn** [comment]
> CreateAccess(CreateAccessRequest) returns (google.protobuf.Empty)
> UpdateAccess(UpdateAccessRequest) returns (google.protobuf.Empty)
> DeleteAccess(DeleteAccessRequest) returns (google.protobuf.Empty)

Is there no situation where any of these can fail? You just send it and you know for sure that your action was performed? Or should it return some sort of response? Maybe it already does and I just dont know how protobuf works?

This also applies to other methods, such as createproject, deleteuser, so forth.

**Comment by atjn** [comment]
> CreateQuery(CreateQueryRequest) returns (google.protobuf.Empty)
> UpdateQuery(UpdateQueryRequest) returns (google.protobuf.Empty)
> DeleteQuery(DeleteQueryRequest) returns (google.protobuf.Empty)

If I understand correctly, we agreed that these should be removed? I understand if you don't have time to do this, but could you then add some comments to make the next software team aware that these are instantly deprecated. Maybe you have already documented this somewhere else, idk.

**Review by Aavild — DISMISSED** [review]

**Comment by Uewotm90** [comment]
> > CreateAccess(CreateAccessRequest) returns (google.protobuf.Empty)
> > UpdateAccess(UpdateAccessRequest) returns (google.protobuf.Empty)
> > DeleteAccess(DeleteAccessRequest) returns (google.protobuf.Empty)
> 
> Is there no situation where any of these can fail? You just send it and you know for sure that your action was performed? Or should it return some sort of response? Maybe it already does and I just dont know how protobuf works?
> 
> This also applies to other methods, such as createproject, deleteuser, so forth.

Status codes are always returned with a given message in addition to the returned data

**Comment by williamwoldum** [comment]
> If I understand correctly, we agreed that these should be removed? I understand if you don't have time to do this, but could you then add some comments to make the next software team aware that these are instantly deprecated. Maybe you have already documented this somewhere else, idk.

I've added a comment

**Review by Aavild — APPROVED** [review]

**Pull request merged**
